### ISSUE TITLE
你好，我在运行您的代码时，出现了 “ Fail to create pixmap with Tk_GetPixmap in TkImgPhotoInstanceSetSize" 的问题，找了很多种方法没有解决。请问您那边有出现该问题吗？该如何解决

### ISSUE THREAD

**Issue by wangshuqiAB** [Cirrick/Multi_UAV_Data_Harvesting#1]

**Comment by Cirrick** [comment]
我运行的时候没有出现过这种问题。你有重新创建一个虚拟环境，然后按照requirements在虚拟环境里面安装各种包嘛，如果没有，我建议你重新建一个虚拟环境在里面安装

**Comment by wangshuqiAB** [comment]
好的，谢谢您，问题已经解决。另外，请问这个代码需要训练多长时间？我在运行plot.py文件时，出现了“No such file or directory: 'dir_1_1/episode_data.npy'”的错误，这个.npy文件时要通过main.py训练生成的吗？

**Comment by Cirrick** [comment]
1. 不加FL大概6-8h。
2. 如果想要运行plot程序，你先需要生成训练数据。
